site_name: 'LSHTM Omics'

theme:
  name: material
  language: en
  features:
    - content.tooltips
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.tabs.link


markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - index.md
    - connecting-github.md
  - Day1: 
      - day1/intro-to-linux.md
      - day1/mapping.md
      - day1/variant-detection.md
  - Day2:
      - day2/nanopore.md
      - day2/assembly-and-third-gen-sequencing.md
      - day2/transcriptomics.md
  - "Other omics":
      - day3/microbiome.md
      - day3/methylation.md
      - day3/eqtl.md
  - "Day 4":
      - day4/phylogenetics.md
      - day4/machine_learning.md
      - day4/gwas.md
      - day4/tb-resistance.md


  - "Additional info":
      - additional-info/conda.md
      - additional-info/software.md
      - additional-info/faq.md
      - additional-info/settingUpYourMachines.md
    #   - additional-info/SettingUpVirtualLinux.md
  - Presentations:
      - presentations/presentations.md
  - Tasks:
      - tasks/intro-to-linux-task.md
      - tasks/variant-calling-task.md
      - tasks/basic-phylogeny-task.md
      - tasks/tb-transcriptomics-task.md

