site_name: 'Mapping'

theme:
  name: material
  language: en
  features:
    - content.tooltips
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.tabs.link


markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Introduction: 
      - introduction/intro-to-linux.md
      - introduction/mapping.md
      - introduction/variant-detection.md
      - introduction/assembly.md
  - Advanced:
      - advanced/phylogenetics.md
      - advanced/third-generation-sequencing.md
      - advanced/gwas.md
  - Other-omics:
      - other-omics/microbiome.md
      - other-omics/transcriptomics.md
      - other-omics/methylation.md
      - other-omics/ml.md
      - other-omics/tb-resistance.md
